### PR TITLE
Rename Sonar project

### PR DESCRIPTION
**Pull request by jkernech**

### CODE REVIEW

**Review by mrister — CHANGES_REQUESTED** [review]
do we need the second file with `~`in it's name ?

**Comment by Spring3** [comment]
Previously you said to remove this part. Which way is correct? https://github.com/dial-once/node-logtify/pull/1#discussion_r118687076

**Comment by jkernech** [comment]
Sorry I didn't push my fixes since I was focusing on fixing the tests

**Review by mrister — APPROVED** [review]

**Comment by jkernech** [comment]
@Spring3 all the projects start with `node-` prefix

**Review by Spring3 — APPROVED** [review]

**Pull request merged**
