### PR TITLE
Add appVersion configuration

### LINKED ISSUE #6: Include appVersion to bugsnag message

### PR DESCRIPTION
**Pull request by Spring3**
resolves #6

### CODE REVIEW

**Review by mrister — APPROVED** [review]

**Review by jkernech — APPROVED** [review]

**Comment by jkernech** [comment]
This means that we will have to maintain two versions one in the env var and one in the `package.json`

**Review by ykhatal — APPROVED** [review]

**Comment by Spring3** [comment]
@ofkindness bump

**Comment by mrister** [comment]
Is there a chance that with a preset we can autopopulate the bugsnag version from package.json ? thus removing that work from client apps.

**Comment by Spring3** [comment]
Yes, I already created an issue in the logtify main module. I will have to slightly adapt Tracer module to be able to do this.

**Pull request merged**
