### PR TITLE
npm audit fix

### PR DESCRIPTION
**Pull request by edunston**
npm audit fix: none breaking changes

### CODE REVIEW

**Review by Spring3 — APPROVED** [review]

**Review by jkernech — APPROVED** [review]

**Review by mrister — CHANGES_REQUESTED** [review]
per this discussion, please remove the lockfile https://github.com/sindresorhus/ama/issues/479

**Review by ykhatal — APPROVED** [review]
As @mrister suggested, please remove the `package-lock.json`

**Comment by edunston** [comment]
All vulnerabilities fixed. All test passed, but one warning `/Users/Eric/Documents/Dial-Once 2017/node-logtify-bugsnag/src/bugsnag-link.js
  39:7  warning  Unexpected console statement  no-console

✖ 1 problem (0 errors, 1 warning)`

**Review by jkernech — APPROVED** [review]

**Review by mrister — APPROVED** [review]
squash before merge plz

**Review by ykhatal — APPROVED** [review]

**Pull request merged**
